[package]
name = "chksum-core"
version = "0.1.0"
authors = ["Konrad Goławski <konrad@golawski.it>"]
edition = "2024"
rust-version = "1.95.0"
description = "Core traits and functions for straightforward hash computation of bytes, files, directories and more."
readme = ".cargo/README.md"
repository = "https://github.com/chksum-rs/core"
license = "MIT"
keywords = ["checksum", "digest", "hash"]
categories = ["algorithms", "cryptography"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-trait = { version = "0.1", optional = true }
chksum-hash-core = "0.0"
thiserror = "2.0"
tokio = { version = "1.42", features = ["fs", "io-util", "io-std"], optional = true }

[dev-dependencies]
tokio = { version = "1.42", features = ["rt", "macros"] }

[features]
default = []

# async runtimes
async-runtime-tokio = ["async-trait", "tokio"]
