name: Rust

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*.yml"
      - "Cargo.toml"
      - "rustfmt.toml"
      - "src/**/*.rs"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/*.yml"
      - "Cargo.toml"
      - "rustfmt.toml"
      - "src/**/*.rs"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Repository checkout
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: Run cargo fmt
        run: cargo fmt --check --verbose
      - name: Run cargo clippy (default features)
        run: cargo clippy --all-targets -- --deny warnings --deny clippy::cargo
      - name: Run cargo clippy (all features)
        run: cargo clippy --all-features --all-targets -- --deny warnings --deny clippy::cargo
      - name: Run cargo doc (all features)
        env:
          RUSTDOCFLAGS: "--cfg docsrs -D warnings"
        run: cargo doc --all-features --no-deps

  build:
    needs:
      - lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [1.95.0, stable, nightly]
        include:
          - os: ubuntu-latest
            os_name: Linux
          - os: macos-latest
            os_name: macOS
          - os: windows-latest
            os_name: Windows
    name: "Build & test (OS: ${{ matrix.os_name }}, Toolchain: ${{ matrix.toolchain }})"
    steps:
      - name: Repository checkout
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Run cargo build (default features)
        run: cargo build --verbose
      - name: Run cargo build (all features)
        run: cargo build --all-features --verbose
      - name: Run cargo test (default features)
        run: cargo test --verbose
      - name: Run cargo test (all features)
        run: cargo test --all-features --verbose
